### ISSUE TITLE
Grid lines and Volume

### ISSUE THREAD

**Issue by boldo** [thegitfather/tradingview-frame#1]
How to remove Grid lines and Volume?

**Comment by thegitfather** [comment]
For volume there is an option top left:
![image](https://user-images.githubusercontent.com/3913533/91869533-4a981b80-ec76-11ea-951d-386947c3eba0.png)

You cant toggle grid/volume by default or I dont see it in the options: https://www.tradingview.com/widget/advanced-chart/
The chart area is a `<canvas>` so you cant manipulate much there..
